### PR TITLE
Update postgresql collector to reflect TLS parameter changes

### PR DESCRIPTION
**Pull request by banjoh**
Relates to https://github.com/replicatedhq/troubleshoot/issues/747. Changes to be released once the implementation is released

### CODE REVIEW

**Review by xavpaice — APPROVED** [review]
LGTM, needs a docs team review

**Review by jonquil2002 — DISMISSED** [review]
lgtm, looks really good overall. Made some style changes. 

Side note: I didn't see a Netlify or other preview available. Maybe this was just my browser, but if a preview can be made available, that really helps.

**Comment by jonquil2002** [comment]
Oh, NOW my browser is rendering a preview. Goodness.

**Review by jonquil2002 — APPROVED** [review]

**Comment by banjoh** [comment]
> lgtm, looks really good overall. Made some style changes.
> 
> Side note: I didn't see a Netlify or other preview available. Maybe this was just my browser, but if a preview can be made available, that really helps.

How do I get access to Netlify previews?

**Pull request merged**
