### PR TITLE
Clarify strict docs

### PR DESCRIPTION
**Pull request by ajp-io**

### CODE REVIEW

**Comment by ajp-io** [comment]
@JustinN-Replicated WDYT of this update? I was interested in how this worked and read the new docs, but I wasn't positive what some of it meant.

**Comment by JustinN-Replicated** [comment]
So the logic to not skip a preflight is a kots thing; people could also use data from `strict = true` as a datapoint to take actions on (like how kots does to block a deploy) but generically it doesn't do anything in troubleshoot standalone (IE we implemented it for our usage of it in KOTS). @pavansokkenagaraj am I missing anything?
Considering, I don't think we can adjust as you had suggested since it would not be accurate

**Comment by ajp-io** [comment]
@JustinN-Replicated That makes sense, thanks for explaining that.

In the current doc, I don't understand this part:
> it provides an additional datapoint for analyzers where `outcomes` should not be ignored.

As someone not involved with this, I don't know what that means or which actions I could take on it. What happens in Troubleshoot when I set that?

**Comment by AmberAlston** [comment]
@JustinN-Replicated @ajp-io - Please either resolve questions and merge this PR, or close as no longer necessary

**Pull request closed without merging**
