### PR TITLE
added details about containerName option

### PR DESCRIPTION
**Pull request by chitender**

### CODE REVIEW

**Comment by manavellamnimble** [comment]
@markpundsack Ok!

**Comment by manavellamnimble** [comment]
@markpundsack Hi mark, the parameter `containerName:` exists and works. I tested it using a multi-container pod

**Comment by manavellamnimble** [comment]
@markpundsack a possible description would be: "It specifies in which container inside the pod will the command be executed. If omitted, the first container in the pod will be chosen."

**Comment by markpundsack** [comment]
Thanks @chitender and @manavellamnimble!

**Review by markpundsack — APPROVED** [review]

**Pull request merged**
