### PR TITLE
change troubleshoot.io to troubleshoot.sh

### PR DESCRIPTION
**Pull request by grantmiller**

### CODE REVIEW

**Review by paigecalvert — APPROVED** [review]
Thanks @grantmiller

**Comment by AmberAlston** [comment]
Do not merge right now. It's not just a docs fix. Troubleshoot team looking into larger issue. Internal slack link - https://replicated.slack.com/archives/C02BPJQQP28/p1679604442705019

**Comment by xavpaice** [comment]
Label updates were released in v0.69.0 that accept the 'old' label, but we need to encourage folks to use `troubleshoot.sh/kind` now.  This is therefore ready for review.

**Review by DexterYan — APPROVED** [review]

**Review by CpuID — APPROVED** [review]
LGTM, did a `grep` over the repo and these were the only references I saw...

Haven't thought through any backwards compatibility implications thoroughly in troubleshoot itself, but just from a docs perspective it's fine.

**Pull request merged**
