### PR TITLE
Fixing broken links; adding 'make test' and CI for links

### PR DESCRIPTION
**Pull request by austinchambers**
Remaining broken links fixed. //golang.org/duration -> https://golang.org/pkg/time/#Duration

Added 'make test' capability to help with validation.

### CODE REVIEW

**Comment by laverya** [comment]
Should 'make test' run in CI?

**Comment by laverya** [comment]
Should 'make test' run in CI?

**Comment by austinchambers** [comment]
Yep, that's my next step. To add CI just like with kots.io.

**Comment by austinchambers** [comment]
Ah, well. Might as well add the CI component here. Added.

**Pull request merged**
